---
title: Versla de keeper
hero_image: images/beat-the-goalie.png
description: Hoeveel doelpunten kun je in 30 seconden maken?
listed: true
copyedit: false
version: 4
last_tested: 2019-02-11
steps:
- title: Inleiding
  completion: engaged
- title: De bal verplaatsen
- title: Was het een doelpunt?
- title: Goal!
- title: Een timer toevoegen
- title: 'Uitdaging: score toevoegen'
  challenge: true
  completion: internal
- title: Bestuur de keeper
- title: 'Uitdaging: handmatige bediening'
  challenge: true
- title: Wat kun je verder nog doen?
