---
title: Versla de keeper
hero_image: images/beat-the-goalie.png
description: Hoeveel doelpunten kun je in 30 seconden maken?
listed: true
copyedit: false
version: 4
last_tested: 2019-02-11
steps:
  - 
    title: Inleiding
  - 
    title: De bal verplaatsen
  - 
    title: Was het een doelpunt?
    completion:
      - engaged
  - 
    title: Goal!
  - 
    title: Een timer toevoegen
  - 
    title: 'Uitdaging: score toevoegen'
    challenge: true
  - 
    title: Bestuur de keeper
    completion:
      - internal
  - 
    title: 'Uitdaging: handmatige bediening'
    challenge: true
  - 
    title: Wat kun je verder nog doen?
