---
hero_image: images/banner.png
theme: red
duration: 1
listed: true
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
title: Beat the Goalie
description: How many goals can you score in 30 seconds?
original_url: https://codeclubprojects.org/en-GB/scratch/beat-the-goalie
interests: ''
technologies: scratch
site_areas: codeclub, scratch
steps:
- title: Introduction
- title: Moving the football
- title: Was it a goal?
- title: 'Challenge: Goal!'
- title: Adding a timer
- title: 'Challenge: Adding a score'
- title: Control the goalie
- title: 'Challenge: More controls'
- title: 'Challenge: Manual control'

