---
title: Schlage den Torwart
hero_image: images/beat-the-goalie.png
description: Wie viele Tore kannst du in 30 Sekunden erzielen?
listed: true
copyedit: false
version: 4
last_tested: 2019-02-11
steps:
  - 
    title: Einleitung
  - 
    title: Den Fußball bewegen
  - 
    title: War das ein Tor?
    completion:
      - engaged
  - 
    title: Tor!
  - 
    title: Hinzufügen eines Timers
  - 
    title: 'Herausforderung: Hinzufügen eines Punktestands'
    challenge: true
  - 
    title: Steuere den Torwart
    completion:
      - internal
  - 
    title: 'Herausforderung: manuelle Steuerung'
    challenge: true
  - 
    title: Wie geht es weiter?
