---
title: Vença o goleiro
hero_image: images/beat-the-goalie.png
description: Quantos gols você consegue marcar em 30 segundos?
listed: true
copyedit: false
version: 4
last_tested: 2019-02-11
steps:
- title: Introdução
- title: Movendo a bola
- title: Foi gol?
  completion:
  - engaged
- title: Gol!
- title: Adicionando um temporizador
- title: 'Desafio: adicionando um placar'
  challenge: true
- title: Controle o goleiro
  completion:
  - internal
- title: 'Desafio: controle manual'
  challenge: true