---
title: تغلب على حارس المرمى
hero_image: images/beat-the-goalie.png
description: كم عدد الأهداف التي يمكنك تسجيلها في 30 ثانية؟
listed: true
copyedit: false
version: 4
last_tested: 2019-02-11
steps:
- title: المقدمة
  completion: engaged
- title: تحريك كرة القدم
- title: هل كان هدفًا؟
- title: هدف!
- title: إضافة مؤقت
- title: 'تحدي: إضافة المزيد من الأهداف'
  challenge: true
  completion: internal
- title: تحكم بحارس المرمى
- title: 'التحدي: التحكم اليدوي'
  challenge: true
- title: ما التالي؟
