---
title: Pokonaj bramkarza
hero_image: images/beat-the-goalie.png
description: Ile goli możesz zdobyć w 30 sekund?
listed: true
copyedit: false
version: 4
last_tested: 2019-02-11
steps:
  - title: Wprowadzenie
  - title: Przenoszenie piłki
  - title: Czy to był gol?
    completion:
      - engaged
  - title: Gol!
  - title: Dodawanie stopera
  - title: 'Wyzwanie: Dodawanie wyniku'
    challenge: true
  - title: Kontroluj bramkarza
    completion:
      - internal
  - title: 'Wyzwanie: sterowanie ręczne'
    challenge: true