---
title: Νίκησε τον τερματοφύλακα
hero_image: images/beat-the-goalie.png
description: Πόσα γκολ μπορείς να βάλεις σε 30 δευτερόλεπτα;
listed: true
copyedit: false
version: 4
last_tested: 2019-02-11
steps:
  - 
    title: Εισαγωγή
  - 
    title: Μετακίνηση ποδοσφαιριστή
  - 
    title: Τι είναι το γκολ;
  - 
    title: Γκολ!
  - 
    title: Προσθήκη χρονομέτρου
  - 
    title: "Πρόκληση: Προσθήκη βαθμολογίας"
    challenge: true
  - 
    title: Έλεγξε τον τερματοφύλακα
  - 
    title: "Πρόκληση: χειροκίνητος έλεγχος"
    challenge: true
  - 
    title: Τι υπάρχει στη συνέχεια;
