---
title: Battre le gardien de but
hero_image: images/beat-the-goalie.png
description: Combien de buts peux-tu marquer en 30 secondes ?
listed: true
copyedit: false
version: 4
last_tested: 2019-02-11
steps:
- title: Introduction
- title: Faire bouger la balle de foot
- title: C'est but ?
  completion:
  - engaged
- title: But !
- title: Ajouter un chronomètre
- title: 'Défi : ajouter un score'
  challenge: true
- title: Contrôler le gardien de but
  completion:
  - internal
- title: 'Défi : contrôle manuel'
  challenge: true
- title: Et ensuite ?
